version: '3.8'

services:
  postgres:
    container_name: ambiflora-db-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ambiflora-db
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres


      